### PR TITLE
Add Install section to README

### LINKED ISSUE #9: Issue deploying the bundle
Hello ,

When trying to deploy this bundle, I had this issue in the jupyter-controller pod:
controller-runtime.source       if kind is a CRD, it should be installed before calling Start   {"kind": "VirtualService.networking.istio.io", "error": "no matches for kind \"VirtualService\" in version \"networking.istio.io/v1alpha3\""}

Seems it's expecting istio to be deployed.

### PR DESCRIPTION
**Pull request by knkski**
Mention where to reference for how to install dependencies

Fixes #9

### CODE REVIEW

**Comment by evilnick** [comment]
Pointing to the  workflow YAML file for install/dependencies instructions probably isn't the best. Are we doing this because those may change frequently? It would be much nicer to just list the commands in the readme if not

I can write out the steps if that helps

**Comment by knkski** [comment]
@evilnick yeah, the concern is that the README would get out-of-sync with what's in the workflow YAML file. I'll leave it up to you as to which option is better

**Comment by evilnick** [comment]
Well, at least some of them aren't likely to change. I will take a pass at it and you can let me know what you think

**Comment by evilnick** [comment]
@knkski I settled for just adding a bit more explanation and hinting that this would be nicer in the future. let me know if that works for you

**Review by ca-scribner — APPROVED** [review]

**Pull request merged**
