### PR TITLE
Kf 4327 feat port jupyter notebook rocks to 1.7

### PR DESCRIPTION
**Pull request by i-chvets**
# Description

Jupyter Notebook ROCK images need to be integrated into `track/1.7` to provide more secure images.

# Summary of changes:
- Updated spawner UI config with references to published ROCK images.

### CODE REVIEW

**Review by DnPlas — COMMENTED** [review]
Thanks @i-chvets , since we are upgrading soon to 1.8.0, does it make sense to have this change approved and merged?

We are about to merge https://github.com/canonical/notebook-operators/pull/302, which updates CRDs and container images.

**Comment by i-chvets** [comment]
> Thanks @i-chvets , since we are upgrading soon to 1.8.0, does it make sense to have this change approved and merged?
> 
> We are about to merge #302, which updates CRDs and container images.

@DnPlas This is for `track/1.7` and should not affect 1.8 work. For 1.8 we will have similar PR for `main`.

**Comment by DnPlas** [comment]
> > Thanks @i-chvets , since we are upgrading soon to 1.8.0, does it make sense to have this change approved and merged?
> > We are about to merge #302, which updates CRDs and container images.
> 
> @DnPlas This is for `track/1.7` and should not affect 1.8 work. For 1.8 we will have similar PR for `main`.

Gotcha, okay. Makes sense, then. Just a comment, your branch seems to be dirty, it has some commits that are already in the `track/1.7` branch, you may want to do a cleanup before we can approve and merge.

**Comment by i-chvets** [comment]
@DnPlas Created clean PR https://github.com/canonical/notebook-operators/pull/303
Closing this PR in favour of https://github.com/canonical/notebook-operators/pull/303

**Pull request closed without merging**
